# Generated by Django 5.2.6 on 2025-10-03 10:29

import tasks.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', tasks.models.CustomUserManager()),
            ],
        ),
    ]
